name: cashier
description: Aplikasi kasir TerasKayuManis — cash-only dan realtime Go.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.4'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.17.2
  flutter_secure_storage: ^11.2.0
  http: ^1.6.0
  uuid: ^4.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3
flutter:
  uses-material-design: true
