begin;
do $$
declare c uuid;p uuid;t uuid;actor uuid:=gen_random_uuid();o jsonb;v jsonb;payload jsonb;oid uuid;deadline timestamptz;
begin
 insert into public.categories(name,slug) values('FLOW','flow-'||actor) returning id into c;
 insert into public.products(category_id,name,slug,price) values(c,'FLOW','flow-'||actor,10000) returning id into p;
 insert into public.tables(number,qr_token) values(99997,'flow-'||actor) returning id into t;
 insert into public.profiles(id,role) values(actor,'cashier');
 payload:=jsonb_build_object('table_token','flow-'||actor,'payment_method','cash','items',jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2,'variant_ids','[]'::jsonb,'addon_ids','[]'::jsonb,'notes','')));
 o:=tkm.checkout('flow-key-'||actor,'flow-access-token-'||actor,payload);oid:=(o->>'id')::uuid;
 if o->>'expires_at' is null then raise exception 'missing expiry';end if;
 deadline:=(o->>'expires_at')::timestamptz;
 begin perform tkm.confirm_cash(oid,actor,20000,1);raise exception 'unreviewed paid accepted';exception when check_violation then null;end;
 v:=tkm.review_order(oid,actor,1,payload->'items');
 update public.products set is_available=false where id=p;
 begin perform tkm.review_order(oid,actor,2,payload->'items');raise exception 'unavailable review accepted';exception when check_violation then null;end;
 if (select version from public.orders where id=oid)<>2 then raise exception 'failed review mutated order';end if;
 update public.products set is_available=true where id=p;
 if v->>'reviewed_version'<>v->>'version' then raise exception 'not reviewed';end if;
 if (v->>'expires_at')::timestamptz<>deadline then raise exception 'review extended timer';end if;
 begin perform tkm.review_order(oid,actor,1,payload->'items');raise exception 'stale review accepted';exception when check_violation then null;end;
 begin perform tkm.confirm_cash(oid,actor,20000,1);raise exception 'stale payment accepted';exception when check_violation then null;end;
 v:=tkm.confirm_cash(oid,actor,20000,2);
 if v->>'payment_status'<>'paid' then raise exception 'payment failed';end if;
 perform tkm.confirm_cash(oid,actor,20000,2);
 update public.orders set created_at=clock_timestamp()-interval '16 minutes' where id=oid;
 perform tkm.expire_orders();
 if (select status from public.orders where id=oid)<>'confirmed' then raise exception 'paid expired';end if;
 o:=tkm.checkout('flow-key-2-'||actor,'flow-access-token-2-'||actor,payload);oid:=(o->>'id')::uuid;
 update public.orders set created_at=clock_timestamp()-interval '15 minutes' where id=oid;
 v:=tkm.review_order(oid,actor,1,payload->'items');
 if v->>'error'<>'expired' then raise exception 'review accepted expired';end if;
 if (select status from public.orders where id=oid)<>'expired' then raise exception 'expiry not persisted';end if;
 if (select count(*) from public.order_status_history where order_id=oid and new_status='expired')<>1 then raise exception 'expiry history';end if;
 perform tkm.expire_orders();
 if (select count(*) from tkm.outbox_events where order_id=oid and event_type='ORDER_EXPIRED')<>1 then raise exception 'duplicate expiry';end if;
 v:=tkm.confirm_cash(oid,actor,20000,1);
 if v->>'error'<>'expired' then raise exception 'expired paid';end if;
 if (select count(*) from public.payments where order_id=oid)<>0 then raise exception 'expired payment record';end if;
 raise notice 'PASS expiry, retained history, review gate, stale versions, retries, paid unaffected';
end $$;
rollback;
